### ISSUE TITLE
Complete the Landing Page

### ISSUE THREAD

**Issue by vishal-codes** [Evozone/dev-call#54]

**Comment by bhargavmodak** [comment]
- Made progress on this with #58 
- Need to add photos
    - Need to discuss what photos to add
- Discussion to add contact info if required

**Comment by vishal-codes** [comment]
Okay, I'll see u on discord.

**Comment by bhargavmodak** [comment]
Completed with #58 
Review and merge please.

**Comment by vishal-codes** [comment]
Yes, I'll try to review the changes by evening.
